
server:
  port: 8083

spring:
  application:
    name: ms-payment
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/payment-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

