server:
  port: 8084

spring:
  application:
    name: ms-delivery
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/delivery-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


